# Python `NumPy` Tutorial

In [2]:
import numpy as np

CURVE_CENTER = 80
grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])

def curve(grades):
    average = grades.mean()
    change = CURVE_CENTER - average
    new_grades = grades + change
    # Clip minimum limits to original grades value and maximum limits to 100
    return np.clip(new_grades, grades, 100)

print(curve(grades))

[ 91.25  54.25  83.25 100.    70.25 100.    93.25  31.25]


In [3]:
import numpy as np

temperatures = np.array([
    29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
    12.6, 49.9, 38.6, 31.3, 9.2, 2.2
]).reshape(2, 2, 3)

print(temperatures.shape)

(2, 2, 3)


In [4]:
np.swapaxes(temperatures, 1, 2)

array([[[29.3, 16.1],
        [42.1, 38. ],
        [18.8, 12.5]],

       [[12.6, 31.3],
        [49.9,  9.2],
        [38.6,  2.2]]])

In [5]:
import numpy as np

table = np.array([
    [5, 3, 7, 1],
    [2, 6, 7, 9],
    [1, 1, 1, 1],
    [4, 3, 2, 0],
])

# Returns the largest value in the entire array
print(table.max())

9


## Using `axis=0` with `.max()`

Selects the maximum value in each of the 4 vertical sets of values in table and returns an array that has been flattened or aggregated into a one-dimensional array.

> `axis=1` will select the maximum value in each of the 4 horizontal sets of values in table

In [6]:
print(table.max(axis=0))

[5 6 7 9]


## Broadcasting

In [8]:
import numpy as np

A = np.arange(32).reshape(4, 1, 8)
print(A)

[[[ 0  1  2  3  4  5  6  7]]

 [[ 8  9 10 11 12 13 14 15]]

 [[16 17 18 19 20 21 22 23]]

 [[24 25 26 27 28 29 30 31]]]


In [9]:
B = np.arange(48).reshape(1, 6, 8)
print(B)

[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30 31]
  [32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47]]]


In [10]:
print(A+B)

[[[ 0  2  4  6  8 10 12 14]
  [ 8 10 12 14 16 18 20 22]
  [16 18 20 22 24 26 28 30]
  [24 26 28 30 32 34 36 38]
  [32 34 36 38 40 42 44 46]
  [40 42 44 46 48 50 52 54]]

 [[ 8 10 12 14 16 18 20 22]
  [16 18 20 22 24 26 28 30]
  [24 26 28 30 32 34 36 38]
  [32 34 36 38 40 42 44 46]
  [40 42 44 46 48 50 52 54]
  [48 50 52 54 56 58 60 62]]

 [[16 18 20 22 24 26 28 30]
  [24 26 28 30 32 34 36 38]
  [32 34 36 38 40 42 44 46]
  [40 42 44 46 48 50 52 54]
  [48 50 52 54 56 58 60 62]
  [56 58 60 62 64 66 68 70]]

 [[24 26 28 30 32 34 36 38]
  [32 34 36 38 40 42 44 46]
  [40 42 44 46 48 50 52 54]
  [48 50 52 54 56 58 60 62]
  [56 58 60 62 64 66 68 70]
  [64 66 68 70 72 74 76 78]]]


## Indexing

In [11]:
import numpy as np

square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])

for i in range(4):
    assert square[:, i].sum() == 34
    assert square[i, :].sum() == 34

assert square[:2, :2].sum() == 34

assert square[2:, :2].sum() == 34

assert square[:2, 2:].sum() == 34

assert square[2:, 2:].sum() == 34

## Transposing, Sorting and Concatenating

In [12]:
import numpy as np

# Transpose an array
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])

# First method
print(a.T)

# Second method
print(a.transpose())

[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


In [14]:
# Sorting an array
data = np.array([
    [7, 1, 4],
    [8, 6, 5],
    [1, 2, 3]
])

print(np.sort(data))
print('\n')
print(np.sort(data, axis=None))
print('\n')
print(np.sort(data, axis=0))

[[1 4 7]
 [5 6 8]
 [1 2 3]]


[1 1 2 3 4 5 6 7 8]


[[1 1 3]
 [7 2 4]
 [8 6 5]]


In [15]:
# Concatenate an array
a = np.array([
    [4, 8],
    [6, 1]
])

b = np.array([
    [3, 5],
    [7, 2],
])

# Stack horizontally
print(np.hstack((a,b)))

[[4 8 3 5]
 [6 1 7 2]]


In [16]:
# Stack vertically
print(np.vstack((b,a)))

[[3 5]
 [7 2]
 [4 8]
 [6 1]]


In [17]:
print(np.concatenate((a,b)))

[[4 8]
 [6 1]
 [3 5]
 [7 2]]


In [19]:
print(np.concatenate((a,b), axis=None))

[4 8 6 1 3 5 7 2]


## Optimizing Storage: Data Types

In [22]:
import numpy as np

a = np.array([1, 3, 5.5, 7.7, 9.2], dtype=np.single)
a

array([1. , 3. , 5.5, 7.7, 9.2], dtype=float32)

In [23]:
b = np.array([1, 3, 5.5, 7.7, 9.2], dtype=np.uint8)
b

array([1, 3, 5, 7, 9], dtype=uint8)

## Structured Arrays

Also known as __record array__ or __structured array__, users can specify a type and optionally, a name on a per-column basis.

In [24]:
import numpy as np

data = np.array([
    ("joe", 32, 6),
    ("mary", 15, 20),
    ("felipe", 80, 100),
    ("beyonce", 38, 9001),
], dtype=[("name", str, 10), ("age", int), ("power", int)])

print(data[0])
print("\n")
print(data["name"])
print("\n")
print(data[data["power"] > 9000]["name"])

('joe', 32, 6)


['joe' 'mary' 'felipe' 'beyonce']


['beyonce']
